name: helm_tag_updater

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_USER: fayvori

jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Code Chechout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: fayvori/helm_tag_updater
            

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: fayvori/helm_tag_updater

  publish_to_pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Chechout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run poetry
        uses: abatilo/actions-poetry@v2

      - name: Change poetry package version
        run: poetry version ${{ github.ref_name }}

      - name: Build and publish to PyPi 
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
